DROP TABLE IF EXISTS person, book CASCADE;
CREATE TABLE person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(100) NOT NULL UNIQUE,
    birthday DATE NOT NULL
);

CREATE TABLE book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES person(id) ON DELETE SET NULL,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    taken_at TIMESTAMP
);